fixed install phase so the linker doesn't abort with undefined reference to pow()
git-svn-id: https://nixos.org/repos/nix/nixpkgs/trunk@10826 70bd8c7a-acb8-0310-9f0d-9cc1c95dcdbb